### ISSUE TITLE
Why an additional LN layer in the feature loss.

### ISSUE THREAD

**Issue by Pay20Y** [LightDXY/BootMAE#1]
Hi, I wonder why an additional LN layer is adopted for the calculating of the feature loss, [here](https://github.com/LightDXY/BootMAE/blob/7a9c26117f18e9c94fde20598e6af0d17109bad7/run_pretraining.py#L459).
Thanks

**Comment by LightDXY** [comment]
hi, it is similar to the pixel norm used in MAE, we use it to normalize the feature and reduce the influence of the absolute value of the features.

**Comment by Pay20Y** [comment]
> hi, it is similar to the pixel norm used in MAE, we use it to normalize the feature and reduce the influence of the absolute value of the features.

Thanks for your quick reply, so why the normalization also applied for the predictions, I mean can it be  "LN(Feat_gt) - out[1]"?

**Comment by LightDXY** [comment]
> > hi, it is similar to the pixel norm used in MAE, we use it to normalize the feature and reduce the influence of the absolute value of the features.
> 
> Thanks for your quick reply, so why the normalization also applied for the predictions, I mean can it be "LN(Feat_gt) - out[1]"?

hi, this makes the model prediction more flexible, the output only needs to have the same normed distribution, but not the absolute value. Its influence is quite minor, removing it will not lead to significant change.

**Comment by Pay20Y** [comment]
> > > hi, it is similar to the pixel norm used in MAE, we use it to normalize the feature and reduce the influence of the absolute value of the features.
> > 
> > 
> > Thanks for your quick reply, so why the normalization also applied for the predictions, I mean can it be "LN(Feat_gt) - out[1]"?
> 
> hi, this makes the model prediction more flexible, the output only needs to have the same normed distribution, but not the absolute value. Its influence is quite minor, removing it will not lead to significant change.

Got it, thanks again!
